version: "3"

services:
  my-jenkins:
    build: ""
    image: brianantony456/my:0.0.1
    ports:
      - 8080:8080
      - 50000:50000

    environment:
      QC_ENV: test

    volumes:
       - /var/jenkins_home:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock